version: '2'

services:
    web:
      image: "lpweb:${BRANCH}"
      build:
        context: .
        args:
          - branch=${BRANCH}
      ports:
        - ${PORT}:80
      volumes:
        - lpweb-logs:/var/log
        - lpweb-data:/usr/share/nginx
      links:
        - postgres
      environment:
        - ADMIN_EMAIL=${CRAFT_ADMIN_EMAIL}
        - ADMIN_USERNAME=${CRAFT_ADMIN_USERNAME}
        - ADMIN_PASSWORD=${CRAFT_ADMIN_PASSWORD}

    postgres:
      image: postgres:11.7
      environment:
        POSTGRES_USER: lpweb
        POSTGRES_PASSWORD: secret
        POSTGRES_DB: lpweb
        POSTGRES_INITDB_ARGS: "-E UTF8"
      volumes:
        - postgresql-data:/var/lib/postgresql/data

volumes:
  lpweb-data:
  lpweb-logs:
  postgresql-data:
